# Generated by Django 4.2.3 on 2023-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_Number',
            new_name='phone_number',
        ),
    ]
